trabFinal/trabFinal/Controllers/LogarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trabFinal.Context;

namespace trabFinal.Controllers
{
    public class LogarController : Controller
    {
        private Contexto db = new Contexto();
        // GET: Logar
        public ActionResult Index(string erro)
        {
            if (erro != null)
            {
                TempData["error"] = erro;
            }

            return View();
        }

        [HttpPost]
        public ActionResult Verificar(Models.LoginModel userModel)
        {
            Models.LoginModel Consultar = (Models.LoginModel)db.logins.FirstOrDefault(u => u.Email == userModel.Email);
            String erro = "Usuário ou senha inválidos";
            if (Consultar == null)
            {
                return RedirectToAction(nameof(Index), new { @erro = erro });
            }

            if (BCrypt.Net.BCrypt.Verify(userModel.Senha, Consultar.Senha))
            {
                Session["Nome"] = Consultar.Username;
                Session["Nivel"] = Consultar.Nivel.ToLower();
                Session.Timeout = 1800;
                return RedirectToAction("Index", "Login");
            }

            return RedirectToAction(nameof(Index), new { @erro = erro });

        }
    }
}

trabFinal/trabFinal/Views/Logar/Index.cshtml
@model trabFinal.Models.LoginModel

@{ 
    Layout = null;
 }
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!doctype html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <link href="~/css/Style2.css" rel="stylesheet" />

    <link rel="icon" href="Favicon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <title>Login</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"></a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <main class="login-form">
        <div class="cotainer">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Faça o Login</div>
                        <div class="card-body">
                            <form action="@Url.Action("Verificar", "Logar")" method="post">
                                <div class="form-group row">
                                    @Html.LabelFor(model => model.Email,
                                        htmlAttributes: new { @class= "col-md-4 col-form-label text-md-right" })
                                    @*<label for="email_address" class="col-md-4 col-form-label text-md-right">E-mail</label>*@
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.Email,
                                            new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email,"",
                                            new { @class = "text-danger"})
                                        @*<input type="text" id="email_address" class="form-control" name="email-address" required autofocus>*@
                                    </div>
                                </div>

                                <div class="form-group row">
                                    @{ if (TempData["error"] != null)
                                        {
                                            var erro = TempData["error"].ToString();
                                            <p class="text-center text-xs text-danger">@erro</p>
                                        }
                                    }
                                    @Html.LabelFor(model => model.Senha,
                                        htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })
                                    @*<label for="password" class="col-md-4 col-form-label text-md-right">Senha</label>*@
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.Senha,
                                            new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Senha, "",
                                            new { @class = "text-danger" })
                                        @*<input type="password" id="password" class="form-control" name="password" required>*@
                                    </div>
                                </div>

                                @*<div class="form-group row">
                                    <div class="col-md-6 offset-md-4">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="remember"> Remember Me
                                            </label>
                                        </div>
                                    </div>
                                </div>*@

                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                        Entrar
                                    </button>
                                    @*<a href="#" class="btn btn-link">
                                        
                                    </a>*@
                                </div>
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        

    </main>

    <hr />
    <br />
    <p>
        Trabalho feito por:
        Lucas Elias de Camargo   Ra:190068
     </p>
    <br />
    <p>
        Gabriel de Mello e Silva Carneiro   Ra:190033
    </p>





</body>
</html>